/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/Hall.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_HallBase : public EntityCall
{
public:

	EntityBaseEntityCall_HallBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_HallBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_HallBase : public EntityCall
{
public:

	EntityCellEntityCall_HallBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_HallBase();
};

}