/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Hall : public HallBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallHallBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/Hall.def
	// Please inherit and implement "class Hall : public HallBase"
class KBENGINEPLUGINS_API HallBase : public Entity
{
public:
	EntityBaseEntityCall_HallBase* pBaseEntityCall;
	EntityCellEntityCall_HallBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	HallBase();
	virtual ~HallBase();

	void attachComponents() override;
	void detachComponents() override;

};

}