/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Player : public PlayerBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallPlayerBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/Player.def
	// Please inherit and implement "class Player : public PlayerBase"
class KBENGINEPLUGINS_API PlayerBase : public Entity
{
public:
	EntityBaseEntityCall_PlayerBase* pBaseEntityCall;
	EntityCellEntityCall_PlayerBase* pCellEntityCall;


	virtual void onUpdateBattle(const CORE_UPDATE_BATLLE_INFO& arg1) = 0; 

	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	PlayerBase();
	virtual ~PlayerBase();

	void attachComponents() override;
	void detachComponents() override;

};

}