/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class PvPRoom : public PvPRoomBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallPvPRoomBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/PvPRoom.def
	// Please inherit and implement "class PvPRoom : public PvPRoomBase"
class KBENGINEPLUGINS_API PvPRoomBase : public Entity
{
public:
	EntityBaseEntityCall_PvPRoomBase* pBaseEntityCall;
	EntityCellEntityCall_PvPRoomBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	PvPRoomBase();
	virtual ~PvPRoomBase();

	void attachComponents() override;
	void detachComponents() override;

};

}