/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class TestEntity : public TestEntityBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallTestEntityBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/TestEntity.def
	// Please inherit and implement "class TestEntity : public TestEntityBase"
class KBENGINEPLUGINS_API TestEntityBase : public Entity
{
public:
	EntityBaseEntityCall_TestEntityBase* pBaseEntityCall;
	EntityCellEntityCall_TestEntityBase* pCellEntityCall;


	virtual void onReqTestProperty(const TEST_ENTITY_PROPS& arg1) = 0; 

	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	TestEntityBase();
	virtual ~TestEntityBase();

	void attachComponents() override;
	void detachComponents() override;

};

}