/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/TestEntity.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_TestEntityBase : public EntityCall
{
public:

	EntityBaseEntityCall_TestEntityBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_TestEntityBase();
	void reqTestProperty();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_TestEntityBase : public EntityCall
{
public:

	EntityCellEntityCall_TestEntityBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_TestEntityBase();
};

}