/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Matcher : public MatcherBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallMatcherBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/Matcher.def
	// Please inherit and implement "class Matcher : public MatcherBase"
class KBENGINEPLUGINS_API MatcherBase : public Entity
{
public:
	EntityBaseEntityCall_MatcherBase* pBaseEntityCall;
	EntityCellEntityCall_MatcherBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	MatcherBase();
	virtual ~MatcherBase();

	void attachComponents() override;
	void detachComponents() override;

};

}