/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	public class EntityBaseEntityCall_AvatarBase : EntityCall
	{

		public EntityBaseEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void reqChangeSelectCard(string arg1)
		{
			Bundle pBundle = newCall("reqChangeSelectCard", 0);
			if(pBundle == null)
				return;

			bundle.writeString(arg1);
			sendCall(null);
		}

		public void reqFinishSelectCards()
		{
			Bundle pBundle = newCall("reqFinishSelectCards", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqLatestBattleInfo()
		{
			Bundle pBundle = newCall("reqLatestBattleInfo", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqSyncHeartBeat()
		{
			Bundle pBundle = newCall("reqSyncHeartBeat", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqUpdateSelectedCard()
		{
			Bundle pBundle = newCall("reqUpdateSelectedCard", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AvatarBase : EntityCall
	{

		public EntityCellEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
