/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			List<DATATYPE_BASE> pAccount_onReqTest_args = new List<DATATYPE_BASE>();
			pAccount_onReqTest_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_onReqTest = new Method();
			pAccount_onReqTest.name = "onReqTest";
			pAccount_onReqTest.methodUtype = 4;
			pAccount_onReqTest.aliasID = 1;
			pAccount_onReqTest.args = pAccount_onReqTest_args;

			pAccountModule.methods["onReqTest"] = pAccount_onReqTest; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqTest.aliasID] = pAccount_onReqTest;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqTest / 4).");

			List<DATATYPE_BASE> pAccount_onSyncRoomCreated_args = new List<DATATYPE_BASE>();
			pAccount_onSyncRoomCreated_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_onSyncRoomCreated = new Method();
			pAccount_onSyncRoomCreated.name = "onSyncRoomCreated";
			pAccount_onSyncRoomCreated.methodUtype = 5;
			pAccount_onSyncRoomCreated.aliasID = 2;
			pAccount_onSyncRoomCreated.args = pAccount_onSyncRoomCreated_args;

			pAccountModule.methods["onSyncRoomCreated"] = pAccount_onSyncRoomCreated; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onSyncRoomCreated.aliasID] = pAccount_onSyncRoomCreated;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onSyncRoomCreated / 5).");

			List<DATATYPE_BASE> pAccount_reqEnterRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_reqEnterRoom = new Method();
			pAccount_reqEnterRoom.name = "reqEnterRoom";
			pAccount_reqEnterRoom.methodUtype = 2;
			pAccount_reqEnterRoom.aliasID = -1;
			pAccount_reqEnterRoom.args = pAccount_reqEnterRoom_args;

			pAccountModule.methods["reqEnterRoom"] = pAccount_reqEnterRoom; 
			pAccountModule.base_methods["reqEnterRoom"] = pAccount_reqEnterRoom;

			pAccountModule.idbase_methods[pAccount_reqEnterRoom.methodUtype] = pAccount_reqEnterRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqEnterRoom / 2).");

			List<DATATYPE_BASE> pAccount_reqMatch_args = new List<DATATYPE_BASE>();

			Method pAccount_reqMatch = new Method();
			pAccount_reqMatch.name = "reqMatch";
			pAccount_reqMatch.methodUtype = 3;
			pAccount_reqMatch.aliasID = -1;
			pAccount_reqMatch.args = pAccount_reqMatch_args;

			pAccountModule.methods["reqMatch"] = pAccount_reqMatch; 
			pAccountModule.base_methods["reqMatch"] = pAccount_reqMatch;

			pAccountModule.idbase_methods[pAccount_reqMatch.methodUtype] = pAccount_reqMatch;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqMatch / 3).");

			List<DATATYPE_BASE> pAccount_reqTest_args = new List<DATATYPE_BASE>();
			pAccount_reqTest_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_reqTest = new Method();
			pAccount_reqTest.name = "reqTest";
			pAccount_reqTest.methodUtype = 1;
			pAccount_reqTest.aliasID = -1;
			pAccount_reqTest.args = pAccount_reqTest_args;

			pAccountModule.methods["reqTest"] = pAccount_reqTest; 
			pAccountModule.base_methods["reqTest"] = pAccount_reqTest;

			pAccountModule.idbase_methods[pAccount_reqTest.methodUtype] = pAccount_reqTest;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqTest / 1).");

			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[2] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 1;
			Vector3 Avatar_position_defval = new Vector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 2;
			Vector3 Avatar_direction_defval = new Vector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 3;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_modelID = new Property();
			pAvatar_modelID.name = "modelID";
			pAvatar_modelID.properUtype = 41006;
			pAvatar_modelID.properFlags = 4;
			pAvatar_modelID.aliasID = 4;
			UInt32 Avatar_modelID_defval;
			UInt32.TryParse("0", out Avatar_modelID_defval);
			pAvatar_modelID.defaultVal = Avatar_modelID_defval;
			pAvatarModule.propertys["modelID"] = pAvatar_modelID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_modelID.aliasID] = pAvatar_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(modelID / 41006).");

			Property pAvatar_modelScale = new Property();
			pAvatar_modelScale.name = "modelScale";
			pAvatar_modelScale.properUtype = 41007;
			pAvatar_modelScale.properFlags = 4;
			pAvatar_modelScale.aliasID = 5;
			Byte Avatar_modelScale_defval;
			Byte.TryParse("30", out Avatar_modelScale_defval);
			pAvatar_modelScale.defaultVal = Avatar_modelScale_defval;
			pAvatarModule.propertys["modelScale"] = pAvatar_modelScale; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_modelScale.aliasID] = pAvatar_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(modelScale / 41007).");

			Property pAvatar_name = new Property();
			pAvatar_name.name = "name";
			pAvatar_name.properUtype = 41003;
			pAvatar_name.properFlags = 4;
			pAvatar_name.aliasID = 6;
			string Avatar_name_defval = "";
			pAvatar_name.defaultVal = Avatar_name_defval;
			pAvatarModule.propertys["name"] = pAvatar_name; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_name.aliasID] = pAvatar_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(name / 41003).");

			Property pAvatar_uid = new Property();
			pAvatar_uid.name = "uid";
			pAvatar_uid.properUtype = 41004;
			pAvatar_uid.properFlags = 4;
			pAvatar_uid.aliasID = 7;
			UInt32 Avatar_uid_defval;
			UInt32.TryParse("0", out Avatar_uid_defval);
			pAvatar_uid.defaultVal = Avatar_uid_defval;
			pAvatarModule.propertys["uid"] = pAvatar_uid; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_uid.aliasID] = pAvatar_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(uid / 41004).");

			Property pAvatar_utype = new Property();
			pAvatar_utype.name = "utype";
			pAvatar_utype.properUtype = 41005;
			pAvatar_utype.properFlags = 4;
			pAvatar_utype.aliasID = 8;
			UInt32 Avatar_utype_defval;
			UInt32.TryParse("0", out Avatar_utype_defval);
			pAvatar_utype.defaultVal = Avatar_utype_defval;
			pAvatarModule.propertys["utype"] = pAvatar_utype; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_utype.aliasID] = pAvatar_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(utype / 41005).");

			List<DATATYPE_BASE> pAvatar_onSyncBattleResult_args = new List<DATATYPE_BASE>();
			pAvatar_onSyncBattleResult_args.Add(EntityDef.id2datatypes[47]);

			Method pAvatar_onSyncBattleResult = new Method();
			pAvatar_onSyncBattleResult.name = "onSyncBattleResult";
			pAvatar_onSyncBattleResult.methodUtype = 22;
			pAvatar_onSyncBattleResult.aliasID = 1;
			pAvatar_onSyncBattleResult.args = pAvatar_onSyncBattleResult_args;

			pAvatarModule.methods["onSyncBattleResult"] = pAvatar_onSyncBattleResult; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncBattleResult.aliasID] = pAvatar_onSyncBattleResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncBattleResult / 22).");

			List<DATATYPE_BASE> pAvatar_onSyncChangeHandCardSuccess_args = new List<DATATYPE_BASE>();
			pAvatar_onSyncChangeHandCardSuccess_args.Add(EntityDef.id2datatypes[2]);
			pAvatar_onSyncChangeHandCardSuccess_args.Add(EntityDef.id2datatypes[1]);
			pAvatar_onSyncChangeHandCardSuccess_args.Add(EntityDef.id2datatypes[1]);

			Method pAvatar_onSyncChangeHandCardSuccess = new Method();
			pAvatar_onSyncChangeHandCardSuccess.name = "onSyncChangeHandCardSuccess";
			pAvatar_onSyncChangeHandCardSuccess.methodUtype = 13;
			pAvatar_onSyncChangeHandCardSuccess.aliasID = 2;
			pAvatar_onSyncChangeHandCardSuccess.args = pAvatar_onSyncChangeHandCardSuccess_args;

			pAvatarModule.methods["onSyncChangeHandCardSuccess"] = pAvatar_onSyncChangeHandCardSuccess; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncChangeHandCardSuccess.aliasID] = pAvatar_onSyncChangeHandCardSuccess;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncChangeHandCardSuccess / 13).");

			List<DATATYPE_BASE> pAvatar_onSyncExhaustCardReplacement_args = new List<DATATYPE_BASE>();

			Method pAvatar_onSyncExhaustCardReplacement = new Method();
			pAvatar_onSyncExhaustCardReplacement.name = "onSyncExhaustCardReplacement";
			pAvatar_onSyncExhaustCardReplacement.methodUtype = 12;
			pAvatar_onSyncExhaustCardReplacement.aliasID = 3;
			pAvatar_onSyncExhaustCardReplacement.args = pAvatar_onSyncExhaustCardReplacement_args;

			pAvatarModule.methods["onSyncExhaustCardReplacement"] = pAvatar_onSyncExhaustCardReplacement; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncExhaustCardReplacement.aliasID] = pAvatar_onSyncExhaustCardReplacement;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncExhaustCardReplacement / 12).");

			List<DATATYPE_BASE> pAvatar_onSyncHeartBeat_args = new List<DATATYPE_BASE>();
			pAvatar_onSyncHeartBeat_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onSyncHeartBeat = new Method();
			pAvatar_onSyncHeartBeat.name = "onSyncHeartBeat";
			pAvatar_onSyncHeartBeat.methodUtype = 20;
			pAvatar_onSyncHeartBeat.aliasID = 4;
			pAvatar_onSyncHeartBeat.args = pAvatar_onSyncHeartBeat_args;

			pAvatarModule.methods["onSyncHeartBeat"] = pAvatar_onSyncHeartBeat; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncHeartBeat.aliasID] = pAvatar_onSyncHeartBeat;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncHeartBeat / 20).");

			List<DATATYPE_BASE> pAvatar_onSyncLatestBattleState_args = new List<DATATYPE_BASE>();
			pAvatar_onSyncLatestBattleState_args.Add(EntityDef.id2datatypes[42]);

			Method pAvatar_onSyncLatestBattleState = new Method();
			pAvatar_onSyncLatestBattleState.name = "onSyncLatestBattleState";
			pAvatar_onSyncLatestBattleState.methodUtype = 21;
			pAvatar_onSyncLatestBattleState.aliasID = 5;
			pAvatar_onSyncLatestBattleState.args = pAvatar_onSyncLatestBattleState_args;

			pAvatarModule.methods["onSyncLatestBattleState"] = pAvatar_onSyncLatestBattleState; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncLatestBattleState.aliasID] = pAvatar_onSyncLatestBattleState;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncLatestBattleState / 21).");

			List<DATATYPE_BASE> pAvatar_onSyncPlayerBattleInfo_args = new List<DATATYPE_BASE>();
			pAvatar_onSyncPlayerBattleInfo_args.Add(EntityDef.id2datatypes[39]);

			Method pAvatar_onSyncPlayerBattleInfo = new Method();
			pAvatar_onSyncPlayerBattleInfo.name = "onSyncPlayerBattleInfo";
			pAvatar_onSyncPlayerBattleInfo.methodUtype = 11;
			pAvatar_onSyncPlayerBattleInfo.aliasID = 6;
			pAvatar_onSyncPlayerBattleInfo.args = pAvatar_onSyncPlayerBattleInfo_args;

			pAvatarModule.methods["onSyncPlayerBattleInfo"] = pAvatar_onSyncPlayerBattleInfo; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncPlayerBattleInfo.aliasID] = pAvatar_onSyncPlayerBattleInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncPlayerBattleInfo / 11).");

			List<DATATYPE_BASE> pAvatar_onSyncResumeBattle_args = new List<DATATYPE_BASE>();
			pAvatar_onSyncResumeBattle_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onSyncResumeBattle = new Method();
			pAvatar_onSyncResumeBattle.name = "onSyncResumeBattle";
			pAvatar_onSyncResumeBattle.methodUtype = 19;
			pAvatar_onSyncResumeBattle.aliasID = 7;
			pAvatar_onSyncResumeBattle.args = pAvatar_onSyncResumeBattle_args;

			pAvatarModule.methods["onSyncResumeBattle"] = pAvatar_onSyncResumeBattle; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncResumeBattle.aliasID] = pAvatar_onSyncResumeBattle;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncResumeBattle / 19).");

			List<DATATYPE_BASE> pAvatar_onSyncRoomStartBattle_args = new List<DATATYPE_BASE>();

			Method pAvatar_onSyncRoomStartBattle = new Method();
			pAvatar_onSyncRoomStartBattle.name = "onSyncRoomStartBattle";
			pAvatar_onSyncRoomStartBattle.methodUtype = 15;
			pAvatar_onSyncRoomStartBattle.aliasID = 8;
			pAvatar_onSyncRoomStartBattle.args = pAvatar_onSyncRoomStartBattle_args;

			pAvatarModule.methods["onSyncRoomStartBattle"] = pAvatar_onSyncRoomStartBattle; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncRoomStartBattle.aliasID] = pAvatar_onSyncRoomStartBattle;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncRoomStartBattle / 15).");

			List<DATATYPE_BASE> pAvatar_onSyncSelectCardInterlude_args = new List<DATATYPE_BASE>();
			pAvatar_onSyncSelectCardInterlude_args.Add(EntityDef.id2datatypes[39]);

			Method pAvatar_onSyncSelectCardInterlude = new Method();
			pAvatar_onSyncSelectCardInterlude.name = "onSyncSelectCardInterlude";
			pAvatar_onSyncSelectCardInterlude.methodUtype = 17;
			pAvatar_onSyncSelectCardInterlude.aliasID = 9;
			pAvatar_onSyncSelectCardInterlude.args = pAvatar_onSyncSelectCardInterlude_args;

			pAvatarModule.methods["onSyncSelectCardInterlude"] = pAvatar_onSyncSelectCardInterlude; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncSelectCardInterlude.aliasID] = pAvatar_onSyncSelectCardInterlude;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncSelectCardInterlude / 17).");

			List<DATATYPE_BASE> pAvatar_onSyncSwitchController_args = new List<DATATYPE_BASE>();
			pAvatar_onSyncSwitchController_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_onSyncSwitchController_args.Add(EntityDef.id2datatypes[5]);

			Method pAvatar_onSyncSwitchController = new Method();
			pAvatar_onSyncSwitchController.name = "onSyncSwitchController";
			pAvatar_onSyncSwitchController.methodUtype = 18;
			pAvatar_onSyncSwitchController.aliasID = 10;
			pAvatar_onSyncSwitchController.args = pAvatar_onSyncSwitchController_args;

			pAvatarModule.methods["onSyncSwitchController"] = pAvatar_onSyncSwitchController; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncSwitchController.aliasID] = pAvatar_onSyncSwitchController;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncSwitchController / 18).");

			List<DATATYPE_BASE> pAvatar_onSyncTimeInterval_args = new List<DATATYPE_BASE>();
			pAvatar_onSyncTimeInterval_args.Add(EntityDef.id2datatypes[44]);

			Method pAvatar_onSyncTimeInterval = new Method();
			pAvatar_onSyncTimeInterval.name = "onSyncTimeInterval";
			pAvatar_onSyncTimeInterval.methodUtype = 16;
			pAvatar_onSyncTimeInterval.aliasID = 11;
			pAvatar_onSyncTimeInterval.args = pAvatar_onSyncTimeInterval_args;

			pAvatarModule.methods["onSyncTimeInterval"] = pAvatar_onSyncTimeInterval; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncTimeInterval.aliasID] = pAvatar_onSyncTimeInterval;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncTimeInterval / 16).");

			List<DATATYPE_BASE> pAvatar_onSyncUpdateSelectedCards_args = new List<DATATYPE_BASE>();
			pAvatar_onSyncUpdateSelectedCards_args.Add(EntityDef.id2datatypes[2]);
			pAvatar_onSyncUpdateSelectedCards_args.Add(EntityDef.id2datatypes[39]);

			Method pAvatar_onSyncUpdateSelectedCards = new Method();
			pAvatar_onSyncUpdateSelectedCards.name = "onSyncUpdateSelectedCards";
			pAvatar_onSyncUpdateSelectedCards.methodUtype = 14;
			pAvatar_onSyncUpdateSelectedCards.aliasID = 12;
			pAvatar_onSyncUpdateSelectedCards.args = pAvatar_onSyncUpdateSelectedCards_args;

			pAvatarModule.methods["onSyncUpdateSelectedCards"] = pAvatar_onSyncUpdateSelectedCards; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSyncUpdateSelectedCards.aliasID] = pAvatar_onSyncUpdateSelectedCards;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSyncUpdateSelectedCards / 14).");

			List<DATATYPE_BASE> pAvatar_reqChangeSelectCard_args = new List<DATATYPE_BASE>();
			pAvatar_reqChangeSelectCard_args.Add(EntityDef.id2datatypes[1]);

			Method pAvatar_reqChangeSelectCard = new Method();
			pAvatar_reqChangeSelectCard.name = "reqChangeSelectCard";
			pAvatar_reqChangeSelectCard.methodUtype = 6;
			pAvatar_reqChangeSelectCard.aliasID = -1;
			pAvatar_reqChangeSelectCard.args = pAvatar_reqChangeSelectCard_args;

			pAvatarModule.methods["reqChangeSelectCard"] = pAvatar_reqChangeSelectCard; 
			pAvatarModule.base_methods["reqChangeSelectCard"] = pAvatar_reqChangeSelectCard;

			pAvatarModule.idbase_methods[pAvatar_reqChangeSelectCard.methodUtype] = pAvatar_reqChangeSelectCard;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqChangeSelectCard / 6).");

			List<DATATYPE_BASE> pAvatar_reqFinishSelectCards_args = new List<DATATYPE_BASE>();

			Method pAvatar_reqFinishSelectCards = new Method();
			pAvatar_reqFinishSelectCards.name = "reqFinishSelectCards";
			pAvatar_reqFinishSelectCards.methodUtype = 7;
			pAvatar_reqFinishSelectCards.aliasID = -1;
			pAvatar_reqFinishSelectCards.args = pAvatar_reqFinishSelectCards_args;

			pAvatarModule.methods["reqFinishSelectCards"] = pAvatar_reqFinishSelectCards; 
			pAvatarModule.base_methods["reqFinishSelectCards"] = pAvatar_reqFinishSelectCards;

			pAvatarModule.idbase_methods[pAvatar_reqFinishSelectCards.methodUtype] = pAvatar_reqFinishSelectCards;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqFinishSelectCards / 7).");

			List<DATATYPE_BASE> pAvatar_reqLatestBattleInfo_args = new List<DATATYPE_BASE>();

			Method pAvatar_reqLatestBattleInfo = new Method();
			pAvatar_reqLatestBattleInfo.name = "reqLatestBattleInfo";
			pAvatar_reqLatestBattleInfo.methodUtype = 10;
			pAvatar_reqLatestBattleInfo.aliasID = -1;
			pAvatar_reqLatestBattleInfo.args = pAvatar_reqLatestBattleInfo_args;

			pAvatarModule.methods["reqLatestBattleInfo"] = pAvatar_reqLatestBattleInfo; 
			pAvatarModule.base_methods["reqLatestBattleInfo"] = pAvatar_reqLatestBattleInfo;

			pAvatarModule.idbase_methods[pAvatar_reqLatestBattleInfo.methodUtype] = pAvatar_reqLatestBattleInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqLatestBattleInfo / 10).");

			List<DATATYPE_BASE> pAvatar_reqSyncHeartBeat_args = new List<DATATYPE_BASE>();

			Method pAvatar_reqSyncHeartBeat = new Method();
			pAvatar_reqSyncHeartBeat.name = "reqSyncHeartBeat";
			pAvatar_reqSyncHeartBeat.methodUtype = 9;
			pAvatar_reqSyncHeartBeat.aliasID = -1;
			pAvatar_reqSyncHeartBeat.args = pAvatar_reqSyncHeartBeat_args;

			pAvatarModule.methods["reqSyncHeartBeat"] = pAvatar_reqSyncHeartBeat; 
			pAvatarModule.base_methods["reqSyncHeartBeat"] = pAvatar_reqSyncHeartBeat;

			pAvatarModule.idbase_methods[pAvatar_reqSyncHeartBeat.methodUtype] = pAvatar_reqSyncHeartBeat;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqSyncHeartBeat / 9).");

			List<DATATYPE_BASE> pAvatar_reqUpdateSelectedCard_args = new List<DATATYPE_BASE>();

			Method pAvatar_reqUpdateSelectedCard = new Method();
			pAvatar_reqUpdateSelectedCard.name = "reqUpdateSelectedCard";
			pAvatar_reqUpdateSelectedCard.methodUtype = 8;
			pAvatar_reqUpdateSelectedCard.aliasID = -1;
			pAvatar_reqUpdateSelectedCard.args = pAvatar_reqUpdateSelectedCard_args;

			pAvatarModule.methods["reqUpdateSelectedCard"] = pAvatar_reqUpdateSelectedCard; 
			pAvatarModule.base_methods["reqUpdateSelectedCard"] = pAvatar_reqUpdateSelectedCard;

			pAvatarModule.idbase_methods[pAvatar_reqUpdateSelectedCard.methodUtype] = pAvatar_reqUpdateSelectedCard;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqUpdateSelectedCard / 8).");

			ScriptModule pGateModule = new ScriptModule("Gate");
			EntityDef.moduledefs["Gate"] = pGateModule;
			EntityDef.idmoduledefs[3] = pGateModule;

			Property pGate_position = new Property();
			pGate_position.name = "position";
			pGate_position.properUtype = 40000;
			pGate_position.properFlags = 4;
			pGate_position.aliasID = 1;
			Vector3 Gate_position_defval = new Vector3();
			pGate_position.defaultVal = Gate_position_defval;
			pGateModule.propertys["position"] = pGate_position; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_position.aliasID] = pGate_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(position / 40000).");

			Property pGate_direction = new Property();
			pGate_direction.name = "direction";
			pGate_direction.properUtype = 40001;
			pGate_direction.properFlags = 4;
			pGate_direction.aliasID = 2;
			Vector3 Gate_direction_defval = new Vector3();
			pGate_direction.defaultVal = Gate_direction_defval;
			pGateModule.propertys["direction"] = pGate_direction; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_direction.aliasID] = pGate_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(direction / 40001).");

			Property pGate_spaceID = new Property();
			pGate_spaceID.name = "spaceID";
			pGate_spaceID.properUtype = 40002;
			pGate_spaceID.properFlags = 16;
			pGate_spaceID.aliasID = 3;
			UInt32 Gate_spaceID_defval;
			UInt32.TryParse("", out Gate_spaceID_defval);
			pGate_spaceID.defaultVal = Gate_spaceID_defval;
			pGateModule.propertys["spaceID"] = pGate_spaceID; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_spaceID.aliasID] = pGate_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(spaceID / 40002).");

			Property pGate_modelID = new Property();
			pGate_modelID.name = "modelID";
			pGate_modelID.properUtype = 41006;
			pGate_modelID.properFlags = 4;
			pGate_modelID.aliasID = 4;
			UInt32 Gate_modelID_defval;
			UInt32.TryParse("0", out Gate_modelID_defval);
			pGate_modelID.defaultVal = Gate_modelID_defval;
			pGateModule.propertys["modelID"] = pGate_modelID; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_modelID.aliasID] = pGate_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(modelID / 41006).");

			Property pGate_modelScale = new Property();
			pGate_modelScale.name = "modelScale";
			pGate_modelScale.properUtype = 41007;
			pGate_modelScale.properFlags = 4;
			pGate_modelScale.aliasID = 5;
			Byte Gate_modelScale_defval;
			Byte.TryParse("30", out Gate_modelScale_defval);
			pGate_modelScale.defaultVal = Gate_modelScale_defval;
			pGateModule.propertys["modelScale"] = pGate_modelScale; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_modelScale.aliasID] = pGate_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(modelScale / 41007).");

			Property pGate_name = new Property();
			pGate_name.name = "name";
			pGate_name.properUtype = 41003;
			pGate_name.properFlags = 4;
			pGate_name.aliasID = 6;
			string Gate_name_defval = "";
			pGate_name.defaultVal = Gate_name_defval;
			pGateModule.propertys["name"] = pGate_name; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_name.aliasID] = pGate_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(name / 41003).");

			Property pGate_uid = new Property();
			pGate_uid.name = "uid";
			pGate_uid.properUtype = 41004;
			pGate_uid.properFlags = 4;
			pGate_uid.aliasID = 7;
			UInt32 Gate_uid_defval;
			UInt32.TryParse("0", out Gate_uid_defval);
			pGate_uid.defaultVal = Gate_uid_defval;
			pGateModule.propertys["uid"] = pGate_uid; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_uid.aliasID] = pGate_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(uid / 41004).");

			Property pGate_utype = new Property();
			pGate_utype.name = "utype";
			pGate_utype.properUtype = 41005;
			pGate_utype.properFlags = 4;
			pGate_utype.aliasID = 8;
			UInt32 Gate_utype_defval;
			UInt32.TryParse("0", out Gate_utype_defval);
			pGate_utype.defaultVal = Gate_utype_defval;
			pGateModule.propertys["utype"] = pGate_utype; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_utype.aliasID] = pGate_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(utype / 41005).");

			pGateModule.useMethodDescrAlias = true;
			ScriptModule pTestEntityModule = new ScriptModule("TestEntity");
			EntityDef.moduledefs["TestEntity"] = pTestEntityModule;
			EntityDef.idmoduledefs[4] = pTestEntityModule;

			Property pTestEntity_position = new Property();
			pTestEntity_position.name = "position";
			pTestEntity_position.properUtype = 40000;
			pTestEntity_position.properFlags = 4;
			pTestEntity_position.aliasID = 1;
			Vector3 TestEntity_position_defval = new Vector3();
			pTestEntity_position.defaultVal = TestEntity_position_defval;
			pTestEntityModule.propertys["position"] = pTestEntity_position; 

			pTestEntityModule.usePropertyDescrAlias = true;
			pTestEntityModule.idpropertys[(UInt16)pTestEntity_position.aliasID] = pTestEntity_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestEntity), property(position / 40000).");

			Property pTestEntity_direction = new Property();
			pTestEntity_direction.name = "direction";
			pTestEntity_direction.properUtype = 40001;
			pTestEntity_direction.properFlags = 4;
			pTestEntity_direction.aliasID = 2;
			Vector3 TestEntity_direction_defval = new Vector3();
			pTestEntity_direction.defaultVal = TestEntity_direction_defval;
			pTestEntityModule.propertys["direction"] = pTestEntity_direction; 

			pTestEntityModule.usePropertyDescrAlias = true;
			pTestEntityModule.idpropertys[(UInt16)pTestEntity_direction.aliasID] = pTestEntity_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestEntity), property(direction / 40001).");

			Property pTestEntity_spaceID = new Property();
			pTestEntity_spaceID.name = "spaceID";
			pTestEntity_spaceID.properUtype = 40002;
			pTestEntity_spaceID.properFlags = 16;
			pTestEntity_spaceID.aliasID = 3;
			UInt32 TestEntity_spaceID_defval;
			UInt32.TryParse("", out TestEntity_spaceID_defval);
			pTestEntity_spaceID.defaultVal = TestEntity_spaceID_defval;
			pTestEntityModule.propertys["spaceID"] = pTestEntity_spaceID; 

			pTestEntityModule.usePropertyDescrAlias = true;
			pTestEntityModule.idpropertys[(UInt16)pTestEntity_spaceID.aliasID] = pTestEntity_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestEntity), property(spaceID / 40002).");

			List<DATATYPE_BASE> pTestEntity_onReqTestProperty_args = new List<DATATYPE_BASE>();
			pTestEntity_onReqTestProperty_args.Add(EntityDef.id2datatypes[28]);

			Method pTestEntity_onReqTestProperty = new Method();
			pTestEntity_onReqTestProperty.name = "onReqTestProperty";
			pTestEntity_onReqTestProperty.methodUtype = 10003;
			pTestEntity_onReqTestProperty.aliasID = 1;
			pTestEntity_onReqTestProperty.args = pTestEntity_onReqTestProperty_args;

			pTestEntityModule.methods["onReqTestProperty"] = pTestEntity_onReqTestProperty; 
			pTestEntityModule.useMethodDescrAlias = true;
			pTestEntityModule.idmethods[(UInt16)pTestEntity_onReqTestProperty.aliasID] = pTestEntity_onReqTestProperty;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestEntity), method(onReqTestProperty / 10003).");

			List<DATATYPE_BASE> pTestEntity_reqTestProperty_args = new List<DATATYPE_BASE>();

			Method pTestEntity_reqTestProperty = new Method();
			pTestEntity_reqTestProperty.name = "reqTestProperty";
			pTestEntity_reqTestProperty.methodUtype = 10001;
			pTestEntity_reqTestProperty.aliasID = -1;
			pTestEntity_reqTestProperty.args = pTestEntity_reqTestProperty_args;

			pTestEntityModule.methods["reqTestProperty"] = pTestEntity_reqTestProperty; 
			pTestEntityModule.base_methods["reqTestProperty"] = pTestEntity_reqTestProperty;

			pTestEntityModule.idbase_methods[pTestEntity_reqTestProperty.methodUtype] = pTestEntity_reqTestProperty;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestEntity), method(reqTestProperty / 10001).");

			ScriptModule pPlayerModule = new ScriptModule("Player");
			EntityDef.moduledefs["Player"] = pPlayerModule;
			EntityDef.idmoduledefs[5] = pPlayerModule;

			Property pPlayer_position = new Property();
			pPlayer_position.name = "position";
			pPlayer_position.properUtype = 40000;
			pPlayer_position.properFlags = 4;
			pPlayer_position.aliasID = 1;
			Vector3 Player_position_defval = new Vector3();
			pPlayer_position.defaultVal = Player_position_defval;
			pPlayerModule.propertys["position"] = pPlayer_position; 

			pPlayerModule.usePropertyDescrAlias = true;
			pPlayerModule.idpropertys[(UInt16)pPlayer_position.aliasID] = pPlayer_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Player), property(position / 40000).");

			Property pPlayer_direction = new Property();
			pPlayer_direction.name = "direction";
			pPlayer_direction.properUtype = 40001;
			pPlayer_direction.properFlags = 4;
			pPlayer_direction.aliasID = 2;
			Vector3 Player_direction_defval = new Vector3();
			pPlayer_direction.defaultVal = Player_direction_defval;
			pPlayerModule.propertys["direction"] = pPlayer_direction; 

			pPlayerModule.usePropertyDescrAlias = true;
			pPlayerModule.idpropertys[(UInt16)pPlayer_direction.aliasID] = pPlayer_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Player), property(direction / 40001).");

			Property pPlayer_spaceID = new Property();
			pPlayer_spaceID.name = "spaceID";
			pPlayer_spaceID.properUtype = 40002;
			pPlayer_spaceID.properFlags = 16;
			pPlayer_spaceID.aliasID = 3;
			UInt32 Player_spaceID_defval;
			UInt32.TryParse("", out Player_spaceID_defval);
			pPlayer_spaceID.defaultVal = Player_spaceID_defval;
			pPlayerModule.propertys["spaceID"] = pPlayer_spaceID; 

			pPlayerModule.usePropertyDescrAlias = true;
			pPlayerModule.idpropertys[(UInt16)pPlayer_spaceID.aliasID] = pPlayer_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Player), property(spaceID / 40002).");

			List<DATATYPE_BASE> pPlayer_onUpdateBattle_args = new List<DATATYPE_BASE>();
			pPlayer_onUpdateBattle_args.Add(EntityDef.id2datatypes[42]);

			Method pPlayer_onUpdateBattle = new Method();
			pPlayer_onUpdateBattle.name = "onUpdateBattle";
			pPlayer_onUpdateBattle.methodUtype = 23;
			pPlayer_onUpdateBattle.aliasID = 1;
			pPlayer_onUpdateBattle.args = pPlayer_onUpdateBattle_args;

			pPlayerModule.methods["onUpdateBattle"] = pPlayer_onUpdateBattle; 
			pPlayerModule.useMethodDescrAlias = true;
			pPlayerModule.idmethods[(UInt16)pPlayer_onUpdateBattle.aliasID] = pPlayer_onUpdateBattle;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Player), method(onUpdateBattle / 23).");

			List<DATATYPE_BASE> pPlayer_onUpdateGridInfoList_args = new List<DATATYPE_BASE>();
			pPlayer_onUpdateGridInfoList_args.Add(EntityDef.id2datatypes[31]);

			Method pPlayer_onUpdateGridInfoList = new Method();
			pPlayer_onUpdateGridInfoList.name = "onUpdateGridInfoList";
			pPlayer_onUpdateGridInfoList.methodUtype = 24;
			pPlayer_onUpdateGridInfoList.aliasID = 2;
			pPlayer_onUpdateGridInfoList.args = pPlayer_onUpdateGridInfoList_args;

			pPlayerModule.methods["onUpdateGridInfoList"] = pPlayer_onUpdateGridInfoList; 
			pPlayerModule.useMethodDescrAlias = true;
			pPlayerModule.idmethods[(UInt16)pPlayer_onUpdateGridInfoList.aliasID] = pPlayer_onUpdateGridInfoList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Player), method(onUpdateGridInfoList / 24).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "ENTITY_SUBSTATE";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "UID";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "ENTITY_UTYPE";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "ENTITY_STATE";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "ENTITY_FORBIDS";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "UID1";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "DIRECTION3D";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "ENTITY_FORBID_COUNTER";
				DATATYPE_ENTITY_FORBID_COUNTER datatype = new DATATYPE_ENTITY_FORBID_COUNTER();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "ENTITYID_LIST";
				DATATYPE_ENTITYID_LIST datatype = new DATATYPE_ENTITYID_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "BAG";
				DATATYPE_BAG datatype = new DATATYPE_BAG();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 27;
				string typeName = "EXAMPLES";
				DATATYPE_EXAMPLES datatype = new DATATYPE_EXAMPLES();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 28;
				string typeName = "TEST_ENTITY_PROPS";
				DATATYPE_TEST_ENTITY_PROPS datatype = new DATATYPE_TEST_ENTITY_PROPS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 29;
				string typeName = "PLAYER_ACTION";
				DATATYPE_PLAYER_ACTION datatype = new DATATYPE_PLAYER_ACTION();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 30;
				string typeName = "UPDATE_GRID_INFO";
				DATATYPE_UPDATE_GRID_INFO datatype = new DATATYPE_UPDATE_GRID_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 31;
				string typeName = "UPDATE_GRID_INFO_LIST";
				DATATYPE_UPDATE_GRID_INFO_LIST datatype = new DATATYPE_UPDATE_GRID_INFO_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 33;
				string typeName = "BATTLE_GRID_INFO";
				DATATYPE_BATTLE_GRID_INFO datatype = new DATATYPE_BATTLE_GRID_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 36;
				string typeName = "SYNC_CARD_INFO";
				DATATYPE_SYNC_CARD_INFO datatype = new DATATYPE_SYNC_CARD_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 39;
				string typeName = "SYNC_PLAYER_BATTLE_INFO";
				DATATYPE_SYNC_PLAYER_BATTLE_INFO datatype = new DATATYPE_SYNC_PLAYER_BATTLE_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 42;
				string typeName = "CORE_UPDATE_BATLLE_INFO";
				DATATYPE_CORE_UPDATE_BATLLE_INFO datatype = new DATATYPE_CORE_UPDATE_BATLLE_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 44;
				string typeName = "SYNC_BATTLE_TIME_INFO";
				DATATYPE_SYNC_BATTLE_TIME_INFO datatype = new DATATYPE_SYNC_BATTLE_TIME_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 45;
				string typeName = "PLAYER_PERSIST_INFO";
				DATATYPE_PLAYER_PERSIST_INFO datatype = new DATATYPE_PLAYER_PERSIST_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 47;
				string typeName = "STRING_LIST";
				DATATYPE_STRING_LIST datatype = new DATATYPE_STRING_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}