/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_lastSelCharacter = new Property();
			pAccount_lastSelCharacter.name = "lastSelCharacter";
			pAccount_lastSelCharacter.properUtype = 2;
			pAccount_lastSelCharacter.properFlags = 32;
			pAccount_lastSelCharacter.aliasID = 4;
			UInt64 Account_lastSelCharacter_defval;
			UInt64.TryParse("0", out Account_lastSelCharacter_defval);
			pAccount_lastSelCharacter.defaultVal = Account_lastSelCharacter_defval;
			pAccountModule.propertys["lastSelCharacter"] = pAccount_lastSelCharacter; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_lastSelCharacter.aliasID] = pAccount_lastSelCharacter;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(lastSelCharacter / 2).");

			List<DATATYPE_BASE> pAccount_onCreateAvatarResult_args = new List<DATATYPE_BASE>();
			pAccount_onCreateAvatarResult_args.Add(EntityDef.id2datatypes[2]);

			Method pAccount_onCreateAvatarResult = new Method();
			pAccount_onCreateAvatarResult.name = "onCreateAvatarResult";
			pAccount_onCreateAvatarResult.methodUtype = 10005;
			pAccount_onCreateAvatarResult.aliasID = 1;
			pAccount_onCreateAvatarResult.args = pAccount_onCreateAvatarResult_args;

			pAccountModule.methods["onCreateAvatarResult"] = pAccount_onCreateAvatarResult; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onCreateAvatarResult.aliasID] = pAccount_onCreateAvatarResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onCreateAvatarResult / 10005).");

			List<DATATYPE_BASE> pAccount_onRemoveAvatar_args = new List<DATATYPE_BASE>();
			pAccount_onRemoveAvatar_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_onRemoveAvatar = new Method();
			pAccount_onRemoveAvatar.name = "onRemoveAvatar";
			pAccount_onRemoveAvatar.methodUtype = 4;
			pAccount_onRemoveAvatar.aliasID = 2;
			pAccount_onRemoveAvatar.args = pAccount_onRemoveAvatar_args;

			pAccountModule.methods["onRemoveAvatar"] = pAccount_onRemoveAvatar; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onRemoveAvatar.aliasID] = pAccount_onRemoveAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onRemoveAvatar / 4).");

			List<DATATYPE_BASE> pAccount_onReqAvatarList_args = new List<DATATYPE_BASE>();

			Method pAccount_onReqAvatarList = new Method();
			pAccount_onReqAvatarList.name = "onReqAvatarList";
			pAccount_onReqAvatarList.methodUtype = 10003;
			pAccount_onReqAvatarList.aliasID = 3;
			pAccount_onReqAvatarList.args = pAccount_onReqAvatarList_args;

			pAccountModule.methods["onReqAvatarList"] = pAccount_onReqAvatarList; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqAvatarList.aliasID] = pAccount_onReqAvatarList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqAvatarList / 10003).");

			List<DATATYPE_BASE> pAccount_onReqTest_args = new List<DATATYPE_BASE>();
			pAccount_onReqTest_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_onReqTest = new Method();
			pAccount_onReqTest.name = "onReqTest";
			pAccount_onReqTest.methodUtype = 5;
			pAccount_onReqTest.aliasID = 4;
			pAccount_onReqTest.args = pAccount_onReqTest_args;

			pAccountModule.methods["onReqTest"] = pAccount_onReqTest; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqTest.aliasID] = pAccount_onReqTest;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqTest / 5).");

			List<DATATYPE_BASE> pAccount_reqAvatarList_args = new List<DATATYPE_BASE>();

			Method pAccount_reqAvatarList = new Method();
			pAccount_reqAvatarList.name = "reqAvatarList";
			pAccount_reqAvatarList.methodUtype = 10001;
			pAccount_reqAvatarList.aliasID = -1;
			pAccount_reqAvatarList.args = pAccount_reqAvatarList_args;

			pAccountModule.methods["reqAvatarList"] = pAccount_reqAvatarList; 
			pAccountModule.base_methods["reqAvatarList"] = pAccount_reqAvatarList;

			pAccountModule.idbase_methods[pAccount_reqAvatarList.methodUtype] = pAccount_reqAvatarList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqAvatarList / 10001).");

			List<DATATYPE_BASE> pAccount_reqCreateAvatar_args = new List<DATATYPE_BASE>();
			pAccount_reqCreateAvatar_args.Add(EntityDef.id2datatypes[2]);
			pAccount_reqCreateAvatar_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqCreateAvatar = new Method();
			pAccount_reqCreateAvatar.name = "reqCreateAvatar";
			pAccount_reqCreateAvatar.methodUtype = 10002;
			pAccount_reqCreateAvatar.aliasID = -1;
			pAccount_reqCreateAvatar.args = pAccount_reqCreateAvatar_args;

			pAccountModule.methods["reqCreateAvatar"] = pAccount_reqCreateAvatar; 
			pAccountModule.base_methods["reqCreateAvatar"] = pAccount_reqCreateAvatar;

			pAccountModule.idbase_methods[pAccount_reqCreateAvatar.methodUtype] = pAccount_reqCreateAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqCreateAvatar / 10002).");

			List<DATATYPE_BASE> pAccount_reqRemoveAvatar_args = new List<DATATYPE_BASE>();
			pAccount_reqRemoveAvatar_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqRemoveAvatar = new Method();
			pAccount_reqRemoveAvatar.name = "reqRemoveAvatar";
			pAccount_reqRemoveAvatar.methodUtype = 2;
			pAccount_reqRemoveAvatar.aliasID = -1;
			pAccount_reqRemoveAvatar.args = pAccount_reqRemoveAvatar_args;

			pAccountModule.methods["reqRemoveAvatar"] = pAccount_reqRemoveAvatar; 
			pAccountModule.base_methods["reqRemoveAvatar"] = pAccount_reqRemoveAvatar;

			pAccountModule.idbase_methods[pAccount_reqRemoveAvatar.methodUtype] = pAccount_reqRemoveAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqRemoveAvatar / 2).");

			List<DATATYPE_BASE> pAccount_reqRemoveAvatarDBID_args = new List<DATATYPE_BASE>();
			pAccount_reqRemoveAvatarDBID_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_reqRemoveAvatarDBID = new Method();
			pAccount_reqRemoveAvatarDBID.name = "reqRemoveAvatarDBID";
			pAccount_reqRemoveAvatarDBID.methodUtype = 3;
			pAccount_reqRemoveAvatarDBID.aliasID = -1;
			pAccount_reqRemoveAvatarDBID.args = pAccount_reqRemoveAvatarDBID_args;

			pAccountModule.methods["reqRemoveAvatarDBID"] = pAccount_reqRemoveAvatarDBID; 
			pAccountModule.base_methods["reqRemoveAvatarDBID"] = pAccount_reqRemoveAvatarDBID;

			pAccountModule.idbase_methods[pAccount_reqRemoveAvatarDBID.methodUtype] = pAccount_reqRemoveAvatarDBID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqRemoveAvatarDBID / 3).");

			List<DATATYPE_BASE> pAccount_reqTest_args = new List<DATATYPE_BASE>();
			pAccount_reqTest_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_reqTest = new Method();
			pAccount_reqTest.name = "reqTest";
			pAccount_reqTest.methodUtype = 1;
			pAccount_reqTest.aliasID = -1;
			pAccount_reqTest.args = pAccount_reqTest_args;

			pAccountModule.methods["reqTest"] = pAccount_reqTest; 
			pAccountModule.base_methods["reqTest"] = pAccount_reqTest;

			pAccountModule.idbase_methods[pAccount_reqTest.methodUtype] = pAccount_reqTest;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqTest / 1).");

			List<DATATYPE_BASE> pAccount_selectAvatarGame_args = new List<DATATYPE_BASE>();
			pAccount_selectAvatarGame_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_selectAvatarGame = new Method();
			pAccount_selectAvatarGame.name = "selectAvatarGame";
			pAccount_selectAvatarGame.methodUtype = 10004;
			pAccount_selectAvatarGame.aliasID = -1;
			pAccount_selectAvatarGame.args = pAccount_selectAvatarGame_args;

			pAccountModule.methods["selectAvatarGame"] = pAccount_selectAvatarGame; 
			pAccountModule.base_methods["selectAvatarGame"] = pAccount_selectAvatarGame;

			pAccountModule.idbase_methods[pAccount_selectAvatarGame.methodUtype] = pAccount_selectAvatarGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(selectAvatarGame / 10004).");

			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[2] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 1;
			Vector3 Avatar_position_defval = new Vector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 2;
			Vector3 Avatar_direction_defval = new Vector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 3;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_level = new Property();
			pAvatar_level.name = "level";
			pAvatar_level.properUtype = 41002;
			pAvatar_level.properFlags = 8;
			pAvatar_level.aliasID = 4;
			UInt16 Avatar_level_defval;
			UInt16.TryParse("", out Avatar_level_defval);
			pAvatar_level.defaultVal = Avatar_level_defval;
			pAvatarModule.propertys["level"] = pAvatar_level; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_level.aliasID] = pAvatar_level;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(level / 41002).");

			Property pAvatar_modelID = new Property();
			pAvatar_modelID.name = "modelID";
			pAvatar_modelID.properUtype = 41006;
			pAvatar_modelID.properFlags = 4;
			pAvatar_modelID.aliasID = 5;
			UInt32 Avatar_modelID_defval;
			UInt32.TryParse("0", out Avatar_modelID_defval);
			pAvatar_modelID.defaultVal = Avatar_modelID_defval;
			pAvatarModule.propertys["modelID"] = pAvatar_modelID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_modelID.aliasID] = pAvatar_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(modelID / 41006).");

			Property pAvatar_modelScale = new Property();
			pAvatar_modelScale.name = "modelScale";
			pAvatar_modelScale.properUtype = 41007;
			pAvatar_modelScale.properFlags = 4;
			pAvatar_modelScale.aliasID = 6;
			Byte Avatar_modelScale_defval;
			Byte.TryParse("30", out Avatar_modelScale_defval);
			pAvatar_modelScale.defaultVal = Avatar_modelScale_defval;
			pAvatarModule.propertys["modelScale"] = pAvatar_modelScale; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_modelScale.aliasID] = pAvatar_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(modelScale / 41007).");

			Property pAvatar_name = new Property();
			pAvatar_name.name = "name";
			pAvatar_name.properUtype = 41003;
			pAvatar_name.properFlags = 4;
			pAvatar_name.aliasID = 7;
			string Avatar_name_defval = "";
			pAvatar_name.defaultVal = Avatar_name_defval;
			pAvatarModule.propertys["name"] = pAvatar_name; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_name.aliasID] = pAvatar_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(name / 41003).");

			Property pAvatar_own_val = new Property();
			pAvatar_own_val.name = "own_val";
			pAvatar_own_val.properUtype = 6;
			pAvatar_own_val.properFlags = 16;
			pAvatar_own_val.aliasID = 8;
			UInt16 Avatar_own_val_defval;
			UInt16.TryParse("", out Avatar_own_val_defval);
			pAvatar_own_val.defaultVal = Avatar_own_val_defval;
			pAvatarModule.propertys["own_val"] = pAvatar_own_val; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_own_val.aliasID] = pAvatar_own_val;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(own_val / 6).");

			Property pAvatar_uid = new Property();
			pAvatar_uid.name = "uid";
			pAvatar_uid.properUtype = 41004;
			pAvatar_uid.properFlags = 4;
			pAvatar_uid.aliasID = 9;
			UInt32 Avatar_uid_defval;
			UInt32.TryParse("0", out Avatar_uid_defval);
			pAvatar_uid.defaultVal = Avatar_uid_defval;
			pAvatarModule.propertys["uid"] = pAvatar_uid; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_uid.aliasID] = pAvatar_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(uid / 41004).");

			Property pAvatar_utype = new Property();
			pAvatar_utype.name = "utype";
			pAvatar_utype.properUtype = 41005;
			pAvatar_utype.properFlags = 4;
			pAvatar_utype.aliasID = 10;
			UInt32 Avatar_utype_defval;
			UInt32.TryParse("0", out Avatar_utype_defval);
			pAvatar_utype.defaultVal = Avatar_utype_defval;
			pAvatarModule.propertys["utype"] = pAvatar_utype; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_utype.aliasID] = pAvatar_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(utype / 41005).");

			List<DATATYPE_BASE> pAvatar_onJump_args = new List<DATATYPE_BASE>();

			Method pAvatar_onJump = new Method();
			pAvatar_onJump.name = "onJump";
			pAvatar_onJump.methodUtype = 9;
			pAvatar_onJump.aliasID = 1;
			pAvatar_onJump.args = pAvatar_onJump_args;

			pAvatarModule.methods["onJump"] = pAvatar_onJump; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onJump.aliasID] = pAvatar_onJump;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onJump / 9).");

			List<DATATYPE_BASE> pAvatar_jump_args = new List<DATATYPE_BASE>();

			Method pAvatar_jump = new Method();
			pAvatar_jump.name = "jump";
			pAvatar_jump.methodUtype = 7;
			pAvatar_jump.aliasID = -1;
			pAvatar_jump.args = pAvatar_jump_args;

			pAvatarModule.methods["jump"] = pAvatar_jump; 
			pAvatarModule.cell_methods["jump"] = pAvatar_jump;

			pAvatarModule.idcell_methods[pAvatar_jump.methodUtype] = pAvatar_jump;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(jump / 7).");

			List<DATATYPE_BASE> pAvatar_relive_args = new List<DATATYPE_BASE>();
			pAvatar_relive_args.Add(EntityDef.id2datatypes[2]);

			Method pAvatar_relive = new Method();
			pAvatar_relive.name = "relive";
			pAvatar_relive.methodUtype = 6;
			pAvatar_relive.aliasID = -1;
			pAvatar_relive.args = pAvatar_relive_args;

			pAvatarModule.methods["relive"] = pAvatar_relive; 
			pAvatarModule.cell_methods["relive"] = pAvatar_relive;

			pAvatarModule.idcell_methods[pAvatar_relive.methodUtype] = pAvatar_relive;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(relive / 6).");

			ScriptModule pGateModule = new ScriptModule("Gate");
			EntityDef.moduledefs["Gate"] = pGateModule;
			EntityDef.idmoduledefs[3] = pGateModule;

			Property pGate_position = new Property();
			pGate_position.name = "position";
			pGate_position.properUtype = 40000;
			pGate_position.properFlags = 4;
			pGate_position.aliasID = 1;
			Vector3 Gate_position_defval = new Vector3();
			pGate_position.defaultVal = Gate_position_defval;
			pGateModule.propertys["position"] = pGate_position; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_position.aliasID] = pGate_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(position / 40000).");

			Property pGate_direction = new Property();
			pGate_direction.name = "direction";
			pGate_direction.properUtype = 40001;
			pGate_direction.properFlags = 4;
			pGate_direction.aliasID = 2;
			Vector3 Gate_direction_defval = new Vector3();
			pGate_direction.defaultVal = Gate_direction_defval;
			pGateModule.propertys["direction"] = pGate_direction; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_direction.aliasID] = pGate_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(direction / 40001).");

			Property pGate_spaceID = new Property();
			pGate_spaceID.name = "spaceID";
			pGate_spaceID.properUtype = 40002;
			pGate_spaceID.properFlags = 16;
			pGate_spaceID.aliasID = 3;
			UInt32 Gate_spaceID_defval;
			UInt32.TryParse("", out Gate_spaceID_defval);
			pGate_spaceID.defaultVal = Gate_spaceID_defval;
			pGateModule.propertys["spaceID"] = pGate_spaceID; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_spaceID.aliasID] = pGate_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(spaceID / 40002).");

			Property pGate_modelID = new Property();
			pGate_modelID.name = "modelID";
			pGate_modelID.properUtype = 41006;
			pGate_modelID.properFlags = 4;
			pGate_modelID.aliasID = 4;
			UInt32 Gate_modelID_defval;
			UInt32.TryParse("0", out Gate_modelID_defval);
			pGate_modelID.defaultVal = Gate_modelID_defval;
			pGateModule.propertys["modelID"] = pGate_modelID; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_modelID.aliasID] = pGate_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(modelID / 41006).");

			Property pGate_modelScale = new Property();
			pGate_modelScale.name = "modelScale";
			pGate_modelScale.properUtype = 41007;
			pGate_modelScale.properFlags = 4;
			pGate_modelScale.aliasID = 5;
			Byte Gate_modelScale_defval;
			Byte.TryParse("30", out Gate_modelScale_defval);
			pGate_modelScale.defaultVal = Gate_modelScale_defval;
			pGateModule.propertys["modelScale"] = pGate_modelScale; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_modelScale.aliasID] = pGate_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(modelScale / 41007).");

			Property pGate_name = new Property();
			pGate_name.name = "name";
			pGate_name.properUtype = 41003;
			pGate_name.properFlags = 4;
			pGate_name.aliasID = 6;
			string Gate_name_defval = "";
			pGate_name.defaultVal = Gate_name_defval;
			pGateModule.propertys["name"] = pGate_name; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_name.aliasID] = pGate_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(name / 41003).");

			Property pGate_uid = new Property();
			pGate_uid.name = "uid";
			pGate_uid.properUtype = 41004;
			pGate_uid.properFlags = 4;
			pGate_uid.aliasID = 7;
			UInt32 Gate_uid_defval;
			UInt32.TryParse("0", out Gate_uid_defval);
			pGate_uid.defaultVal = Gate_uid_defval;
			pGateModule.propertys["uid"] = pGate_uid; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_uid.aliasID] = pGate_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(uid / 41004).");

			Property pGate_utype = new Property();
			pGate_utype.name = "utype";
			pGate_utype.properUtype = 41005;
			pGate_utype.properFlags = 4;
			pGate_utype.aliasID = 8;
			UInt32 Gate_utype_defval;
			UInt32.TryParse("0", out Gate_utype_defval);
			pGate_utype.defaultVal = Gate_utype_defval;
			pGateModule.propertys["utype"] = pGate_utype; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_utype.aliasID] = pGate_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(utype / 41005).");

			pGateModule.useMethodDescrAlias = true;
			ScriptModule pTestEntityModule = new ScriptModule("TestEntity");
			EntityDef.moduledefs["TestEntity"] = pTestEntityModule;
			EntityDef.idmoduledefs[4] = pTestEntityModule;

			Property pTestEntity_position = new Property();
			pTestEntity_position.name = "position";
			pTestEntity_position.properUtype = 40000;
			pTestEntity_position.properFlags = 4;
			pTestEntity_position.aliasID = 1;
			Vector3 TestEntity_position_defval = new Vector3();
			pTestEntity_position.defaultVal = TestEntity_position_defval;
			pTestEntityModule.propertys["position"] = pTestEntity_position; 

			pTestEntityModule.usePropertyDescrAlias = true;
			pTestEntityModule.idpropertys[(UInt16)pTestEntity_position.aliasID] = pTestEntity_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestEntity), property(position / 40000).");

			Property pTestEntity_direction = new Property();
			pTestEntity_direction.name = "direction";
			pTestEntity_direction.properUtype = 40001;
			pTestEntity_direction.properFlags = 4;
			pTestEntity_direction.aliasID = 2;
			Vector3 TestEntity_direction_defval = new Vector3();
			pTestEntity_direction.defaultVal = TestEntity_direction_defval;
			pTestEntityModule.propertys["direction"] = pTestEntity_direction; 

			pTestEntityModule.usePropertyDescrAlias = true;
			pTestEntityModule.idpropertys[(UInt16)pTestEntity_direction.aliasID] = pTestEntity_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestEntity), property(direction / 40001).");

			Property pTestEntity_spaceID = new Property();
			pTestEntity_spaceID.name = "spaceID";
			pTestEntity_spaceID.properUtype = 40002;
			pTestEntity_spaceID.properFlags = 16;
			pTestEntity_spaceID.aliasID = 3;
			UInt32 TestEntity_spaceID_defval;
			UInt32.TryParse("", out TestEntity_spaceID_defval);
			pTestEntity_spaceID.defaultVal = TestEntity_spaceID_defval;
			pTestEntityModule.propertys["spaceID"] = pTestEntity_spaceID; 

			pTestEntityModule.usePropertyDescrAlias = true;
			pTestEntityModule.idpropertys[(UInt16)pTestEntity_spaceID.aliasID] = pTestEntity_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestEntity), property(spaceID / 40002).");

			List<DATATYPE_BASE> pTestEntity_onReqTestProperty_args = new List<DATATYPE_BASE>();
			pTestEntity_onReqTestProperty_args.Add(EntityDef.id2datatypes[28]);

			Method pTestEntity_onReqTestProperty = new Method();
			pTestEntity_onReqTestProperty.name = "onReqTestProperty";
			pTestEntity_onReqTestProperty.methodUtype = 10003;
			pTestEntity_onReqTestProperty.aliasID = 1;
			pTestEntity_onReqTestProperty.args = pTestEntity_onReqTestProperty_args;

			pTestEntityModule.methods["onReqTestProperty"] = pTestEntity_onReqTestProperty; 
			pTestEntityModule.useMethodDescrAlias = true;
			pTestEntityModule.idmethods[(UInt16)pTestEntity_onReqTestProperty.aliasID] = pTestEntity_onReqTestProperty;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestEntity), method(onReqTestProperty / 10003).");

			List<DATATYPE_BASE> pTestEntity_reqTestProperty_args = new List<DATATYPE_BASE>();

			Method pTestEntity_reqTestProperty = new Method();
			pTestEntity_reqTestProperty.name = "reqTestProperty";
			pTestEntity_reqTestProperty.methodUtype = 10001;
			pTestEntity_reqTestProperty.aliasID = -1;
			pTestEntity_reqTestProperty.args = pTestEntity_reqTestProperty_args;

			pTestEntityModule.methods["reqTestProperty"] = pTestEntity_reqTestProperty; 
			pTestEntityModule.base_methods["reqTestProperty"] = pTestEntity_reqTestProperty;

			pTestEntityModule.idbase_methods[pTestEntity_reqTestProperty.methodUtype] = pTestEntity_reqTestProperty;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestEntity), method(reqTestProperty / 10001).");

			ScriptModule pPlayerModule = new ScriptModule("Player");
			EntityDef.moduledefs["Player"] = pPlayerModule;
			EntityDef.idmoduledefs[5] = pPlayerModule;

			Property pPlayer_position = new Property();
			pPlayer_position.name = "position";
			pPlayer_position.properUtype = 40000;
			pPlayer_position.properFlags = 4;
			pPlayer_position.aliasID = 1;
			Vector3 Player_position_defval = new Vector3();
			pPlayer_position.defaultVal = Player_position_defval;
			pPlayerModule.propertys["position"] = pPlayer_position; 

			pPlayerModule.usePropertyDescrAlias = true;
			pPlayerModule.idpropertys[(UInt16)pPlayer_position.aliasID] = pPlayer_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Player), property(position / 40000).");

			Property pPlayer_direction = new Property();
			pPlayer_direction.name = "direction";
			pPlayer_direction.properUtype = 40001;
			pPlayer_direction.properFlags = 4;
			pPlayer_direction.aliasID = 2;
			Vector3 Player_direction_defval = new Vector3();
			pPlayer_direction.defaultVal = Player_direction_defval;
			pPlayerModule.propertys["direction"] = pPlayer_direction; 

			pPlayerModule.usePropertyDescrAlias = true;
			pPlayerModule.idpropertys[(UInt16)pPlayer_direction.aliasID] = pPlayer_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Player), property(direction / 40001).");

			Property pPlayer_spaceID = new Property();
			pPlayer_spaceID.name = "spaceID";
			pPlayer_spaceID.properUtype = 40002;
			pPlayer_spaceID.properFlags = 16;
			pPlayer_spaceID.aliasID = 3;
			UInt32 Player_spaceID_defval;
			UInt32.TryParse("", out Player_spaceID_defval);
			pPlayer_spaceID.defaultVal = Player_spaceID_defval;
			pPlayerModule.propertys["spaceID"] = pPlayer_spaceID; 

			pPlayerModule.usePropertyDescrAlias = true;
			pPlayerModule.idpropertys[(UInt16)pPlayer_spaceID.aliasID] = pPlayer_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Player), property(spaceID / 40002).");

			List<DATATYPE_BASE> pPlayer_onUpdateBattle_args = new List<DATATYPE_BASE>();
			pPlayer_onUpdateBattle_args.Add(EntityDef.id2datatypes[34]);

			Method pPlayer_onUpdateBattle = new Method();
			pPlayer_onUpdateBattle.name = "onUpdateBattle";
			pPlayer_onUpdateBattle.methodUtype = 10;
			pPlayer_onUpdateBattle.aliasID = 1;
			pPlayer_onUpdateBattle.args = pPlayer_onUpdateBattle_args;

			pPlayerModule.methods["onUpdateBattle"] = pPlayer_onUpdateBattle; 
			pPlayerModule.useMethodDescrAlias = true;
			pPlayerModule.idmethods[(UInt16)pPlayer_onUpdateBattle.aliasID] = pPlayer_onUpdateBattle;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Player), method(onUpdateBattle / 10).");

			List<DATATYPE_BASE> pPlayer_onUpdateGridInfoList_args = new List<DATATYPE_BASE>();
			pPlayer_onUpdateGridInfoList_args.Add(EntityDef.id2datatypes[31]);

			Method pPlayer_onUpdateGridInfoList = new Method();
			pPlayer_onUpdateGridInfoList.name = "onUpdateGridInfoList";
			pPlayer_onUpdateGridInfoList.methodUtype = 11;
			pPlayer_onUpdateGridInfoList.aliasID = 2;
			pPlayer_onUpdateGridInfoList.args = pPlayer_onUpdateGridInfoList_args;

			pPlayerModule.methods["onUpdateGridInfoList"] = pPlayer_onUpdateGridInfoList; 
			pPlayerModule.useMethodDescrAlias = true;
			pPlayerModule.idmethods[(UInt16)pPlayer_onUpdateGridInfoList.aliasID] = pPlayer_onUpdateGridInfoList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Player), method(onUpdateGridInfoList / 11).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "ENTITY_SUBSTATE";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "UID";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "ENTITY_UTYPE";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "ENTITY_STATE";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "ENTITY_FORBIDS";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "UID1";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "DIRECTION3D";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "ENTITY_FORBID_COUNTER";
				DATATYPE_ENTITY_FORBID_COUNTER datatype = new DATATYPE_ENTITY_FORBID_COUNTER();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "ENTITYID_LIST";
				DATATYPE_ENTITYID_LIST datatype = new DATATYPE_ENTITYID_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "BAG";
				DATATYPE_BAG datatype = new DATATYPE_BAG();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 27;
				string typeName = "EXAMPLES";
				DATATYPE_EXAMPLES datatype = new DATATYPE_EXAMPLES();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 28;
				string typeName = "TEST_ENTITY_PROPS";
				DATATYPE_TEST_ENTITY_PROPS datatype = new DATATYPE_TEST_ENTITY_PROPS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 29;
				string typeName = "PLAYER_ACTION";
				DATATYPE_PLAYER_ACTION datatype = new DATATYPE_PLAYER_ACTION();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 30;
				string typeName = "UPDATE_GRID_INFO";
				DATATYPE_UPDATE_GRID_INFO datatype = new DATATYPE_UPDATE_GRID_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 31;
				string typeName = "UPDATE_GRID_INFO_LIST";
				DATATYPE_UPDATE_GRID_INFO_LIST datatype = new DATATYPE_UPDATE_GRID_INFO_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 33;
				string typeName = "BATTLE_GRID_INFO";
				DATATYPE_BATTLE_GRID_INFO datatype = new DATATYPE_BATTLE_GRID_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 34;
				string typeName = "CORE_UPDATE_BATLLE_INFO";
				DATATYPE_CORE_UPDATE_BATLLE_INFO datatype = new DATATYPE_CORE_UPDATE_BATLLE_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}